### ISSUE TITLE
temporary disable "auto indent" before doing clipboard paste

### ISSUE THREAD

**Issue by unxed** [magiblot/turbo#1]
...or some text is being pasted with unnecessary spaces (this sample is copied from turbo's readme on github in firefox):
```
Building

First of all, you should clone this repository along its submodules with git clone --recursive.

Then, make sure the following dependencies are installed:

    CMake.
        A compiler supporting C++17.
            libncursesw (note the 'w').
                libfmt.
                
```

**Comment by magiblot** [comment]
It is currently not possible to detect a 'paste' event from the terminal (except system clipboard, #2). It would be first necessary to add non-blocking event look-ahead support in Turbo Vision.

**Comment by magiblot** [comment]
A terrible workaround would be to measure the time between text events in order to make an approximate 'paste' detection.

**Comment by unxed** [comment]
> A terrible workaround would be to measure the time between text events in order to make an approximate 'paste' detection.

Not so terrible, Midnight Commander is doing just the same to prevent the need of pressing ESC twice.

**Comment by magiblot** [comment]
I am very obstinate, so instead of doing the timing hack I ended up implementing non-blocking event reads in Turbo Vision to make this feature possible.

**Comment by unxed** [comment]
Tested. Working. Cool!

**Comment by magiblot** [comment]
This is now also implemented in `tvedit`.

**Comment by unxed** [comment]
It turns out that there is a standard solution to this problem, supported by most terminals:
https://en.wikipedia.org/wiki/Bracketed-paste
https://invisible-island.net/xterm/xterm-paste64.html
