### ISSUE TITLE
deb ?

### ISSUE THREAD

**Issue by stuaxo** [magiblot/turbo#10]
Hi,
   Any chance of a deb for debian/ubuntu ?

Cheers
S

**Comment by magiblot** [comment]
Hi Stuart! Thanks for your interest. I'll quote myself from https://github.com/magiblot/turbo/issues/4#issuecomment-713176084:

> Yes, this would be great, but for this to work a package has to be created and published in a repository and maintained by someone. I don't know how to do this and I'm not even using the same Linux distribution as you. I don't have the time to be a package maintainer either. So I'm sorry but I can't promise you this.

I'm sorry.

I don't know if they will be of any use to you, but you can find Windows binaries in the "Artifacts" section of Actions: https://github.com/magiblot/turbo/actions/runs/388934901

**Comment by stuaxo** [comment]
Completely understandable, it was worth asking.   I'm sure someone will do this in the end, it might even be me one day when there is free time.

I'll close this and head over to #4 :)

Thanks for Turbo, I'm sure it won't be long until issues around Linux will be sorted.

**Comment by amay5267** [comment]
Hi stuaxo

What architecture are you interested in?
Is it for arm64 on Raspberry pi?
Or maybe amd64?
Can you run and provide this command from console:
uname -v

**Comment by stuaxo** [comment]
Hi,
 I'm mostly based on amd64, I've got raspberry pis running both 32 and 64 bit arm.
Can't paste uname output right now as I'm typing this on my phone.

Cheers
S

**Comment by amay5267** [comment]
Hi @stuaxo 
Check this out! 
[turbo_1.0-1_arm64.deb.zip](https://github.com/magiblot/turbo/files/10136632/turbo_1.0-1_arm64.deb.zip)

**Comment by stuaxo** [comment]
Fantastic, I will try this later :)

**Comment by stuaxo** [comment]
Success on amd 64 on Ubuntu 22.04 - looks great with modern fonts, also fooled me well enough that I immediately tried to full screen it via alt-enter !

**Comment by amay5267** [comment]
Hi @magiblot @stuaxo 
Success on amd 64 on Debian "Testing" 12. 
No success on Debian 11.5 "Stable" because of this dependencies : glibc_2.34 and glibcxx_3.4.29

**Comment by alexmyczko** [comment]
here's a debian source package (unfinished, but building, installable, runnable):

http://sid.ethz.ch/debian/turbo/

**Comment by amay5267** [comment]
here are my unofficial builds including Debian and Ubuntu:

https://software.opensuse.org//download.html?project=home%3Aamay5267&package=turbo
