### ISSUE TITLE
FreeBSD port

### ISSUE THREAD

**Issue by vampiebar** [magiblot/turbo#13]
I will try to make freebsd port of this and add some feature to make it full c++ ide for now

**Comment by magiblot** [comment]
Okay. There is no reason why this shouldn't work on FreeBSD by default, though: if it fails to compile or run, it needs to be fixed. I will take a look at it later.

**Comment by vampiebar** [comment]
It is already working :)
both tvision and turbo looks working

**Comment by magiblot** [comment]
Good!

**Comment by vampiebar** [comment]
![shot-2021-01-25_18-09-32](https://user-images.githubusercontent.com/1489223/105724771-45937b80-5f39-11eb-87a0-6961a1fc4abc.jpg)


ldd turbo 
turbo:
	libncursesw.so.8 => /lib/libncursesw.so.8 (0x800683000)
	libxcb.so.1 => /usr/local/lib/libxcb.so.1 (0x8006e5000)
	libmagic.so.4 => /usr/lib/libmagic.so.4 (0x800712000)
	libc++.so.1 => /usr/lib/libc++.so.1 (0x80073c000)
	libcxxrt.so.1 => /lib/libcxxrt.so.1 (0x800809000)
	libm.so.5 => /lib/libm.so.5 (0x80082b000)
	libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x80085d000)
	libthr.so.3 => /lib/libthr.so.3 (0x800877000)
	libc.so.7 => /lib/libc.so.7 (0x8008a4000)
	libXau.so.6 => /usr/local/lib/libXau.so.6 (0x800c9a000)
	libXdmcp.so.6 => /usr/local/lib/libXdmcp.so.6 (0x800c9f000)
	libz.so.6 => /lib/libz.so.6 (0x800ca7000)

**Comment by vampiebar** [comment]
I am happy now I will try to find a way for lsp binding for scintilla

**Comment by danfe** [comment]
Just have [added it](https://www.freshports.org/editors/turbo/) to the FreeBSD Ports Collection.

**Comment by magiblot** [comment]
Thanks for the interest, @danfe!
