### ISSUE TITLE
Can't clone the repository

### ISSUE THREAD

**Issue by acgt1** [magiblot/turbo#21]
I tried `git clone` and `gh repo clone magiblot/turbo`, none of them work. I constantly get credentials error which is weird as this repository suppose to be read-only public repo, isn't it?

example for `git`:
$ git clone --recursive https://github.com/magiblot/turbo.git
Cloning into 'turbo'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

example for `gh`:
$ gh repo clone magiblot/turbo
Cloning into 'turbo'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
exit status 128

**Comment by magiblot** [comment]
Hi @acgt1!

The full command is:

```
git clone --recursive https://github.com/magiblot/turbo
```

Sorry for the inconvenience.

**Comment by magiblot** [comment]
Hi @acgt1!

> $ git clone --recursive https://github.com/magiblot/turbo.git
> Cloning into 'turbo'...
> git@github.com: Permission denied (publickey).
> fatal: Could not read from remote repository.

Mhm... this command should have worked.

Does it work if you try with `gitlab.com` instead of `github.com`?

```
git clone --recursive https://gitlab.com/magiblot/turbo.git
```

**Comment by acgt1** [comment]
with gitlab it works perfectly :)

**Comment by acgt1** [comment]
Now the submodules are being problematic, seems like they are against github too:

Example:
Submodule 'deps/fmt' (https://github.com/fmtlib/fmt) registered for path 'deps/fmt'
Submodule 'libclipboard' (https://github.com/jtanx/libclipboard.git) registered for path 'deps/libclipboard'
Submodule 'deps/tvision' (https://github.com/magiblot/tvision) registered for path 'deps/tvision'
Cloning into '~~~~~~turbo/deps/fmt'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by acgt1** [comment]
I offer to update .gitmodule and open them to the public:
[submodule "deps/tvision"]
	path = deps/tvision
	url = https://gitlab.com/magiblot/tvision
[submodule "deps/fmt"]
	path = deps/fmt
	url = https://gitlab.com/fmtlib/fmt
[submodule "libclipboard"]
	path = deps/libclipboard
	url = https://gitlab.com/jtanx/libclipboard.git

specifically `fmt` and `libclibpboard.git`, I think tvision is OK

**Comment by acgt1** [comment]
Eventually I solved it by adding an SSH key to my profile. I don't think it's an issue with your repo. I don't remember that github enforced a login + key (a recent change!?).
So, for gitlab, I suggest to move the submodules to gitlab as well. As for the github repo, it might be wroth to drop it altogether once you finish a complete move to gitlab to avoid confusion, maybe you can keep the a pointer to gitlab.
This is just an advice, not a request, it will definitely help a less experienced audience ;)
I'm now going to play with your editor, it looks promising!

**Comment by magiblot** [comment]
Ah, good to know you eventually solved the issue.

Gitlab works for turbo and tvision because coincidentally I published them there too. I do not own the other submodules, so I cannot "move" them to Gitlab.

It doesn't matter whether the repos are in Gitlab or Github; `git clone` should work out-of-the box in either case. This is the first time I have heard about an issue like yours, so I don't have a clue what may have caused it. I suspect there may have been something wrong in your SSH or Git settings, but I don't know.

What I should do is place the complete `git clone` command in the Readme.

Please note that, as the Readme mentions, this editor lacks some basic features.

Cheers!
