### ISSUE TITLE
Expired binaries

### ISSUE THREAD

**Issue by tomaszwaraksa** [magiblot/turbo#22]
Hi, the latest binaries under Action / Builds are now expired. Any chance you could run the build again? 

And thanks for the outstanding work! It's so good that I'm just advertising it to my little circle: https://letsdebug.it/post/28-turbo-editor/

**Comment by magiblot** [comment]
Hi Tomas! Thanks for the comment, thanks for the blog post and sorry for having left the binaries unattended. I just ran a new build and artifacts are available again.

Cheers!
