### ISSUE TITLE
Can't replace text

### ISSUE THREAD

**Issue by eda2z** [magiblot/turbo#25]
Very nice job. I have been using SciTE for a long time, I am tired of vi/vim, I refused to learn emacs a long time ago, and I tried textadept curses but it can't handle shift-arrow if you are not it a terminal emulator. Turbo really brings back memories... I have not tried everything but I can't seem to get replace to work. Ctrl+R does nothing and selecting it from the Edit menu also does nothing - the menu doesn't even close. I am running on the latest Arch linux. Other color schemes would be nice. I was going to try and experiment with the code but I figured I'd break something. Thanks for your efforts.

**Comment by magiblot** [comment]
The Replace feature has been finally implemented.
