### ISSUE TITLE
Weirdness when resizing under windows.

### ISSUE THREAD

**Issue by leimath** [magiblot/turbo#28]
![image](https://user-images.githubusercontent.com/96306150/168521000-53d24346-04c4-4921-8b8a-fc9d43d8fa91.png)
![2022-05-16-000062](https://user-images.githubusercontent.com/96306150/168521034-196ec599-62b8-4e37-bc27-dda0b1895ac8.png)

I have made similar issues for other text editors (vim, helix) so I am not looking for a fix but rather what causes this ? As in why does resizing breaks text editors on windows whereas macOS and linux work fine. If someone happens to know the cause, would be good to know the underlying reason.

**Comment by magiblot** [comment]
Hi leimath!

In the case of Turbo this has nothing to do with Windows. It's just that the logic of resizing the subwindows is crappy and it needs to be fixed. At least that's what I can tell from the screenshots you shared.

Regarding the other editors, the thing is that the Win32 Console API is completely different from Unix's console model. Adding Windows support to an application that was first written with Unix in mind may require great structural changes, so my guess is that most of these applications simply have poor Windows support.

Cheers.

**Comment by leimath** [comment]
Thanks for the explanation! That helps my curiosity. So there is nothing much that can be done by the looks of it and gui editors will be the way to go here. 

I am closing this issue since my query is answered. Thanks again!
