### ISSUE TITLE
List of recently opened files

### ISSUE THREAD

**Issue by amay5267** [magiblot/turbo#29]
hi magiblot

i am going to implement this new feature called List of recently opened files in Turbo.
it it ok to save/open recently opened files metadata as/from JSON file ?
is it ok using parser - dropbox/json11 ?
if yes, i am going to write own recently opened files metadata cpp json writer.

**Comment by magiblot** [comment]
Okay! Go ahead!

**Comment by amay5267** [comment]
Do you prefer json11 or rapidjson?

**Comment by magiblot** [comment]
RapidJSON is apparently better.

**Comment by amay5267** [comment]
let me try nlohmann - json

**Comment by magiblot** [comment]
Yes, of course.
