### ISSUE TITLE
some unicode chars are processed wrong

### ISSUE THREAD

**Issue by unxed** [magiblot/turbo#3]
Sample attached.

How to reproduce?
1. Open this file
2. Try to delete the right square bracket using backspace key

[sample.txt](https://github.com/magiblot/turbo/files/5401384/sample.txt)

**Comment by magiblot** [comment]
Cool, thanks for noticing.

**Comment by magiblot** [comment]
Unxed, I can't see anything strange.

Here is what I see after deleting the right square bracket, in four different terminal emulators (Konsole, GNOME Terminal, Terminology, Kitty):

![Screenshot_20201024_203358](https://user-images.githubusercontent.com/20713561/97090941-4e259e80-1638-11eb-9108-f19610d113c6.png)

So let me ask you:

* What terminal are you using?
* What is your locale? Mine is `es_ES.utf8`, and `en_US.utf8` also works well.
* Do you see the same issue in the `tvedit` demo application?

Cheers.

**Comment by unxed** [comment]
Re-checked. You are right, it reproduces only in far2l internal terminal and only in graphics version of far2l. It's a problem of terminal, not turbo, right?

**Comment by magiblot** [comment]
> It's a problem of terminal, not turbo, right?

That's right.
