### ISSUE TITLE
Toggle Line Comments

### ISSUE THREAD

**Issue by amay5267** [magiblot/turbo#34]
hi @magiblot 

Can we toggle line comments with CTRL-/  shortcut?

**Comment by magiblot** [comment]
Hi @amay5267!

I may be able to add this, although it will certainly need a shortcut other than `Ctrl+/` (since most Unix terminals don't support it).

What programming language do you need comments for?

**Comment by amay5267** [comment]
OK. CPP, Python, Java, C.
I need
CPP single line comments
// cpp comment 
Python
# python comment
Java multi-line comment
/* java
comment */
And single and multi line comments in C.

thanks

**Comment by amay5267** [comment]
OK. C, CPP, Python.
I need
CPP single line comments
// cpp comment
Python
python # comment
And single and multi line comments in C.
/* C
you later */

**Comment by magiblot** [comment]
This has been implemented this in 395c02fac82e17c6e00f6489ea4ecb701e75b899. The shortcut is `Ctrl+Q`, as in SciTE, but the behaviour is like in Kate. That is, it automatically chooses between line or block comments depending on the text selection:

* No selection: line comments (`//`)
* Whole lines selected: line comments (`//`)
* Selection beginning and/or ending in the middle of a line: block comments (`/* */`)

If the language supports just one kind of comment, then that's the one that is always used.

**Comment by amay5267** [comment]
Works like a charm!
