### ISSUE TITLE
icon

### ISSUE THREAD

**Issue by amay5267** [magiblot/turbo#51]
Hi @magiblot

turbo needs an icon.

**Comment by magiblot** [comment]
Hi @amay5267,

Why do you think an icon is necessary?

**Comment by amay5267** [comment]
Hi @magiblot 

Icon is essential part of a great user experience.
48x48 png will be fine.

**Comment by magiblot** [comment]
But are you on Windows?

**Comment by magiblot** [comment]
I was able to add an icon for Windows and even macOS. In Linux and other Unixes it is not possible to embed icons into applications.

**Comment by amay5267** [comment]
It works like a charm on my macOS.
