### ISSUE TITLE
install TARGETS given target "fmt" which does not exist.

### ISSUE THREAD

**Issue by dodona2** [magiblot/turbo#55]
Result of cmake . -DCMAKE_BUILD_TYPE=Release 
Status: R

CMake Error at deps/CMakeLists.txt:24 (add_subdirectory):
  The source directory

    /usr/local/src/sdm/turbo/trunk/deps/fmt

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:81 (include)

CMake Error at deps/CMakeLists.txt:34 (add_subdirectory):
  The source directory

    /usr/local/src/sdm/turbo/trunk/deps/tvision
Call Stack (most recent call first):
  CMakeLists.txt:81 (include)

CMake Error at deps/CMakeLists.txt:34 (add_subdirectory):
  The source directory

    /usr/local/src/sdm/turbo/trunk/deps/tvision

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:81 (include)

CMake Error at CMakeLists.txt:110 (install):
  install TARGETS given target "fmt" which does not exist.

-- Configuring incomplete, errors occurred!

  does not contain a CMakeLists.txt file.

**Comment by magiblot** [comment]
Hi @dodona2!

It looks like your clone of Turbo does not contain the submodules, hence the error.

If you cloned Turbo manually, then this should be enough:

```sh
cd /usr/local/src/sdm/turbo/trunk
git submodule init
git submodule update
```

If you downloaded Turbo through a package manager, then you should report this issue to the package maintainer.
