### ISSUE TITLE
segfault

### ISSUE THREAD

**Issue by unxed** [magiblot/turbo#61]
The latest version of turbo from the master crashes with a segmentation fault:
```
Program received signal SIGSEGV, Segmentation fault.
                                                    __strlen_sse2 () at ../sysdeps/x86_64/multiarch/strlen-vec.S:126
```

**Comment by unxed** [comment]
On Ubuntu 18.04 error is different:
![изображение](https://github.com/magiblot/turbo/assets/1151423/ba387dba-7f38-492e-8783-10c5add7a4ef)

**Comment by magiblot** [comment]
Hi @unxed!

Thank you very much for the report, and sorry for the trouble. I had been unaware of this issue because it would not show up in debug builds.
