### ISSUE TITLE
use `text-editor` as a topic

### ISSUE THREAD

**Issue by maddes8cht** [magiblot/turbo#76]
This is a really great Project!
Thanks for your work!
I was looking for an easy-to use Terminal editor like this for ages. 
I've become somewhat familiar with Helix, while yedit from yori still lacks some very basic features, like syntax highlighting. 

I would never have found `turbo` if someone hadn't pointed it out to me. If you're looking for a terminal text editor, it's very hard to find.
To make this project a little more visible (and perhaps attract the attention of potential contributors), I would strongly recommend working on the `topics` you can assign in the `about` section of the repository.
Most text editors I know have a `text editor` topic (I wonder why), some also have a 'code editor' topic (or even both). If you search for a text editor, you will search for a topic like this.  You may rather drop some of the topics like `linux`, `linux-console`, `utf-8`etc. The main point of your projects is that it is a text-editor, so make that visible.

And again:
This is a really great project, i really like it! Thank you!

**Comment by magiblot** [comment]
Hi @maddes8cht!

Thank you for the kind words. I'm glad to know that I was able to meet your expectations with Turbo, even though it is still missing essential features.

Thanks for the suggestion as well. I wasn't aware about the `text-editor` topic.

Cheers!
