### ISSUE TITLE
case-insensitive search for non-latin letters

### ISSUE THREAD

**Issue by unxed** [magiblot/turbo#8]
Currently "Edit->Find" function is case insensitive for latin, but case sensitive for cyrillic. Probably this behavior should be consistent independently of language used.

**Comment by magiblot** [comment]
Thanks for noticing. I'll have to check how Scintilla handles this.

By the way, can you provide a sample text for testing purposes?

**Comment by unxed** [comment]
For sure! Searching for "задача" should find "Задача", searching for "разнообразный" should find "Разнообразный", searching for "товарищи" should find "Товарищи".

[test.txt](https://github.com/magiblot/turbo/files/5635825/test.txt)
